all:
	@echo "Minix Package Manager, version `cat etc/version`"
	@echo ""
	@echo "    make all                 this message"
	@echo "    make easypack            create an easypack package"
	@echo "    make clean               delete temporary files"
	@echo "    make distclean           same as clean"
	@echo ""

easypack:
	@echo "not implemented yet"

clean:
	rm -f *~ */*~

distclean:	clean

