all:
	@echo "MPMPORTS/MINIX Bootdisk"
	@echo ""
	@echo "targets:"
	@echo ""
	@echo "fd0         create bootdisk on /dev/fd0"
	@echo "extract     extract image from /dev/fd0 and write to bootdisk.img"
	@echo ""

fd0:
	./mk.fd0.sh
