#! /bin/sh

dst=`basename "$1"`
base=`basename $dst .c`

cat "$1" | sed -e "s/^int main/int main_$base/" \
               -e "s/^void main/void main_$base/" \
               -e "s/^main(/main_$base(/" \
               \
               -e 's/^void \*allocate/static void \*allocate/' \
               -e 's/^char \*whoami(/static char \*whoami(/' \
               -e 's/^char \*basename(/static char \*basename(/' \
               -e 's/^char \*getold(/static char \*getold(/' \
               -e 's/^char \*getnew(/static char \*getnew(/' \
               -e 's/^char \*alloc(/static char \*alloc(/' \
               -e 's/^void \*xmalloc(/static void \*xmalloc(/' \
               -e 's/^void \*xrealloc(/static void \*xrealloc(/' \
               \
               -e 's/^int copy(/static int copy(/' \
               -e 's/^int find/static int find/' \
               -e 's/^int compare/static int compare/' \
               -e 's/^int eat_dir(/static int eat_dir(/' \
               -e 's/^int cmp(/static int cmp(/' \
               -e 's/^int check(/static int check(/' \
               -e 's/^int print(/static int print(/' \
               -e 's/^int read_line(/static int read_line(/' \
               -e 's/^int length(/static int length(/' \
               -e 's/^int split/static int split/' \
               -e 's/^int newfile(/static int newfile(/' \
               -e 's/^int read_header(/static int read_header(/' \
               -e 's/^int match/static int match/' \
               -e 's/^int uniq(/static int uniq(/' \
               -e 's/^void usage(/static void usage(/' \
               -e 's/^void report(/static void report(/' \
               -e 's/^void calendar(/static void calendar(/' \
               -e 's/^void error(/static void error(/' \
               -e 's/^void regerror(/static void regerror(/' \
               -e 's/^void fatal(/static void fatal(/' \
               -e 's/^void fname(/static void fname(/' \
               -e 's/^void svcname(/static void svcname(/' \
               -e 's/^void Usage(/static void Usage(/' \
               -e 's/^void output(/static void output(/' \
               -e 's/^void onintr/static void onintr/' \
               -e 's/^void crc/static void crc/' \
               -e 's/^void addpath/static void addpath/' \
               -e 's/^void warn/static void warn/' \
               -e 's/^void dumphunk/static void dumphunk/' \
               -e 's/^void range(/static void range(/' \
               -e 's/^void deallocate(/static void deallocate(/' \
               -e 's/^void compress(/static void compress(/' \
               -e 's/^void print(/static void print(/' \
               -e 's/^void execute(/static void execute(/' \
               -e 's/^void makedir(/static void makedir(/' \
               -e 's/^void number(/static void number(/' \
               -e 's/^void timeout(/static void timeout(/' \
               -e 's/^void path_init(/static void path_init(/' \
               -e 's/^void path_add(/static void path_add(/' \
               -e 's/^void path_trunc(/static void path_trunc(/' \
               -e 's/^void get_inode(/static void get_inode(/' \
               -e 's/^void get_block(/static void get_block(/' \
               -e 's/^void getline(/static void getline(/' \
               -e 's/^void flush(/static void flush(/' \
               -e 's/^void tell(/static void tell(/' \
               -e 's/^void done(/static void done(/' \
               -e 's/^void quit(/static void quit(/' \
               -e 's/^void sort(/static void sort(/' \
               -e 's/^void check(/static void check(/' \
               -e 's/^void open_outfile(/static void open_outfile(/' \
               -e 's/^void print_table(/static void print_table(/' \
               -e 's/^void check_file(/static void check_file(/' \
               -e 's/^void strip(/static void strip(/' \
               -e 's/^void copy(/static void copy(/' \
               -e 's/^void extract(/static void extract(/' \
               -e 's/^void delete(/static void delete(/' \
               -e 's/^void do_chown(/static void do_chown(/' \
               -e 's/^void mread(/static void mread(/' \
               -e 's/^void mwrite(/static void mwrite(/' \
               -e 's/^void print_time(/static void print_time(/' \
               -e 's/^void convert(/static void convert(/' \
               -e 's/^void expand(/static void expand(/' \
               -e 's/^void compare(/static void compare(/' \
               -e 's/^void err(/static void err(/' \
               -e 's/^void show(/static void show(/' \
               -e 's/^void format(/static void format(/' \
               -e 's/^void doprnt(/static void doprnt(/' \
               -e 's/^void intr(/static void intr(/' \
               -e 's/^void usage /static void usage /' \
               -e 's/^void printname(/static void printname(/' \
               -e 's/^void list(/static void list(/' \
               -e 's/^int getline(/static int getline(/' \
               -e 's/^void gettable/static void gettable/' \
               -e 's/^mode_t parsemode(/static mode_t parsemode(/' \
               -e 's/^block_t sizeup(/static block_t sizeup(/' \
               -e 's/^prettyprog/static prettyprog/' \
               -e 's/^source(/static source(/' \
               \
               -e 's/^\(int force[^_]\)/static \1/' \
               -e 's/^\(int all[^_;]\)/static \1/' \
               -e 's/^\(int copy[^_]\)/static \1/' \
               -e 's/^int plen/static int plen/' \
               -e 's/^int version /static int version /' \
               -e 's/^int column/static int column/' \
               -e 's/^int table/static int table/' \
               -e 's/^int debug/static int debug/' \
               -e 's/^int ncols/static int ncols/' \
               -e 's/^int quiet/static int quiet/' \
               -e 's/^int done/static int done/' \
               -e 's/^int xdev=/static int xdev=/' \
               -e 's/^int excode/static int excode/' \
               -e 's/^int iflag/static int iflag/' \
               -e 's/^int inode_offset/static int inode_offset/' \
               -e 's/^int verbose/static int verbose/' \
               -e 's/^int override/static int override/' \
               -e 's/^int dflag/static int dflag/' \
               -e 's/^int cflag/static int cflag/' \
               -e 's/^int fields/static int fields/' \
               -e 's/^int part /static int part /' \
               -e 's/^int rflag/static int rflag/' \
               -e 's/^int list/static int list/' \
               -e 's/^short int verbose/static short int verbose/' \
               -e 's/^char table/static char table/' \
               -e 's/^char usage/static char usage/' \
               -e 's/^char PATH_UTMP/static char PATH_UTMP/' \
               -e 's/^char copyright/static char copyright/' \
               -e 's/^unsigned int /static unsigned int /' \
               > $dst

